# -*- coding: utf-8 -*-
"""Object Detection with Colab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1abpr6f8ga5_zQhNew-mtrf50uyBWvvfq
"""

!git clone https://github.com/WongKinYiu/yolov7.git

cd yolov7/

!pip install -r requirements.txt

# !pip install torch==1.8.1+cu111 torchvision==0.9.1+cu111 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
# import torch
# torch.cuda.is_available()

!wget https://farm1.staticflickr.com/25/47371695_31d59fc184_z.jpg -q -O image.jpg

!python detect.py --weights yolov7.pt --conf 0.5 --img-size 640 --source ./image.jpg

#video
!python detect.py --weights yolov7.pt --conf 0.25 --img-size 640 --source /content/vidoe2.mov